name: Release

on:
  push:
    branches:
      - main

jobs:
  checkout:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Checkout repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 # Fetch-depth 0 necessary to get full commit history for checking changes

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

  auth:
    needs: [checkout]
    runs-on: ubuntu-latest
    name: Authenticate to GitHub Registry
    steps:
      - uses: exile-watch/doryani/auth-github-registry@main
        with:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  cqa:
    needs: [auth]
    runs-on: ubuntu-latest
    name: Code Quality Assurance
    steps:
      - uses: exile-watch/doryani/code-quality-assurance@main
        with:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    needs: [cqa]
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Lerna publish
        if: success()
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna publish --yes